import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
// import AuthProvider from "./auth/provider";
import localFont from "next/font/local";
import AuthProvider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"] });

const sanfrancisco = localFont({
  src: "../public/fonts/san_francisco-webfont.woff2",
  adjustFontFallback: "Times New Roman",
  variable: "--fonts-sanfrancisco",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    title: "Learn Next js",
    description: "My First Next js Website!",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <body className={`${inter.className} ${sanfrancisco.variable}`}>
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
